### ISSUE TITLE
[question] is there a config where I can define if players inventory slots should remain locked on death?

### ISSUE THREAD

**Issue by MSandro** [Ladysnake/Locki#2]
I noticed that the inventory slots were unlocked after death. So you can currently bypass the unlock quest in my modpack and unlock your inventory earlier. It's not what I imagined.

**Comment by MSandro** [comment]
In the meantime I should be able to write a workaround with KubeJS. But it would be nice if you could implement such a configuration. Thank you.

**Comment by Pyrofab** [comment]
Right, this should be fairly easy to fix.

**Comment by MSandro** [comment]
Thank you, if possible also please for 1.16.5.

**Comment by Pyrofab** [comment]
I can probably backport this fix to 1.16.5, but I can't say I will do the same for other improvements. I don't really have the time to support multiple versions sadly :/

**Comment by MSandro** [comment]
Thanks, that helps me a lot.
